version: "3.7"
services:
  postgres:
    image: dockerinaction/postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: example
  mariadb:
    image: dockerinaction/mariadb:10-bionic
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: dockerinaction/adminer:4
    ports:
      - 8081:8080
    deploy:
      replicas: 3
