version: "3.7"
networks:
  foo:
    driver: overlay
volumes:
  pgdata: # empty definition uses volume defaults
services:
  postgres:
    image: dockerinaction/postgres:11-alpine
    volumes:
      - type: volume
        source: pgdata # The named volume above
        target: /var/lib/postgresql/data
    networks:
      - foo
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: dockerinaction/adminer:4
    networks:
      - foo
    ports:
      - 8081:8080
    deploy:
      replicas: 1