version: "3.7"
services:
  postgres:
    image: dockerinaction/postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: dockerinaction/adminer:4
    ports:
      - 8080:8080
    deploy:
      replicas: 2
